### ISSUE TITLE
Why split first and then cat instead of clone in the same dimension?

### ISSUE THREAD

**Issue by xinxing277** [KVishnuVardhanR/M3T#7]
Your work is great and it makes it much easier for me to read the paper. But I have some questions when reading the code. In the MultiPlane_MultiSlice_Extract_Project module, why do you split first and then cat in the same dimension instead of clone?
![image](https://github.com/KVishnuVardhanR/M3T/assets/58331146/e9069fa3-0c4c-45ca-916a-44f8e2427b07)

**Comment by KVishnuVardhanR** [comment]
Hi, 

good question. we can just clone the input tensor 3 times and call them as Ecor, Esag, Eax instead of splitting and concatenating along same dimension. But, according to the paper, we are calculating the features from the extraction operator. So, instead of cloning I perform these operations such that it aligns with intuition of this extracting the features in different planes. 

I know that this may look like redundant operation, but I believe this process explains the need for performing this operation.
<img width="337" alt="Screenshot 2024-07-04 at 9 31 33 AM" src="https://github.com/KVishnuVardhanR/M3T/assets/33771427/409da4bd-127e-460b-a078-9a7c0e15f167">

Duplicating the tensor 3 times and naming them differently does not explain the intuition of extracting the features in different planes. However, I will update the readme file, such that when implementing you may choose to use clone instead.

Let me know your thoughts,
Vishnu
